DEVICE_PATH := device/infinix/x6840

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a

TARGET_BOARD_PLATFORM := mt6768
TARGET_NO_KERNEL := false
BOARD_USES_RECOVERY_AS_BOOT := true

BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT := true

OF_MAINTAINER := "Opreker Infinix"
OF_DEVICE_WITHOUT_PERSIST := 1
OF_QUICK_BACKUP_LIST := "/boot;/vendor_boot;/data;"
FOX_MAINTAINER_PATCH_VERSION := 1

